Create training sets.

diff --git a/bin/create-training-sets b/bin/create-training-sets
--- a/bin/create-training-sets
+++ b/bin/create-training-sets
@@ -1,19 +1,46 @@
 #!/bin/bash
 
+# Copyright 2017 Eddie Antonio Santos <easantos@ualberta.ca>
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#   http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+
+# Exports the training set's source files to directories that mirror
+# evaluation/<language>/partitions
+#
+# Usage:
+#   create-training-sets MAX
+
+
 parent="$(dirname "$0")"
 repository_root="$(realpath "$parent/..")"
 
-for language in python java javascript; do
+max="$1"
+
+if ! [[ "$max" =~ ^[0-9]+$ ]] ; then
+   echo "Not a positive integer $max" >&2; exit 1
+fi
+
+for language in python javascript java; do
     for part in {0..4}; do
         dir="$language/partitions/$part/training"
         hashes="$repository_root/evaluation/$dir"
         if [ ! -r "$hashes" ] ; then
-            echo "Could not find hashes: $hashes" 2>&1
-            exit 2
+            echo "Could not find hashes: $hashes" >&2; exit 2
         fi
         output_dir="$repository_root/subset/$dir"
         # Run the actual program with a valid environment
-        env PATH="$PATH:$parent" SENSIBILITY_LANGAGE="$language"\
-            save-source-files "$output_dir" <"$hashes"
+        head -n"$max" "$hashes" |\
+            env PATH="$PATH:$parent" SENSIBILITY_LANGUAGE="$language"\
+            save-source-files "$output_dir"
     done
 done
